name: Setup Admin

on:
  repository_dispatch:
    types: [configurar-admin-token]

jobs:
  save-admin-token:
    runs-on: ubuntu-latest

    steps:
      - name: Validar evento
        run: |
          echo "Evento recebido: ${{ github.event.action }}"
          echo "Payload: ${{ github.event.client_payload.adminToken }}" | sed 's/./*/g'

      - name: Configurar Secret (requer permissões manuais)
        run: |
          echo "⚠️ Importante: o GitHub Actions não pode criar/atualizar secrets sozinho."
          echo "Cole o token admin manualmente em: https://github.com/${{ github.repository }}/settings/secrets/actions"
          echo "Nome do secret sugerido: TPL_ADMIN_TOKEN"
