name: Setup Admin

on:
  repository_dispatch:
    types: [configurar-admin-token]

jobs:
  confirm-admin-token:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir confirmação
        run: |
          echo "Evento recebido: configurar-admin-token"
          echo "Um Personal Access Token foi enviado pelo front-end."
          echo "⚠️ Atenção: o GitHub Actions não pode salvar secrets automaticamente."
          echo "Já que você cadastrou o Secret ADMIN_BOOTSTRAP_PAT manualmente,"
          echo "não é necessário fazer mais nada aqui."
